import { BigNumber, FixedNumber } from '@ethersproject/bignumber'
import { ContractApis } from '../api/contract-apis'
import { RAY } from '../utils'

/**
 * This object represents a GEB safe. It has the entire SAFE state and provides helper functions to calculate its liquidation price, collateralization ratio etc.
 */
export class Safe {
    constructor(
        private contracts: ContractApis,

        /**
         * SAFE handler in the SAFE Engine
         */
        public handler: string,
        /**
         * Amount of debt generated by the SAFE (WAD)
         */
        public debt: BigNumber,
        /**
         * Amount of collateral locked in the SAFE (WAD)
         */
        public collateral: BigNumber,
        /**
         * SAFE collateral type
         */
        public collateralType: string,
        /**
         * Whether the safe was opened using a SAFE manager or not
         */
        public isManaged: boolean,
        /**
         * Safe incremental ID, only for managed safes
         */
        public safeId?: number
    ) {}
}
